on:
  pull_request:

jobs:
  android-unit-tests:
    name: "Run unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '17'
      - name: "chmod gradlew"
        run: chmod +x ./gradlew
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest
